spring:
    application:
        name: email-service
    cloud:
        config:
        uri: http://localhost:8888
        fail-fast: true
    mail:
      host: smtp.gmail.com
      port: 587
      username: ${SMTP_USER_NAME:}
      password: ${SMTP_PASSWORD:}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
          debug: true