spring:
    application:
        name: email-service
    cloud:
        config:
        uri: http://localhost:8888
        fail-fast: true
    mail:
      host: smtp.gmail.com
      port: 587
      username: chidananda676gmail.com
      password: my-password
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
          debug: true